# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [5]:
import numpy as np
x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [8]:
import numpy as np
v=np.array([[0,0,0],[0,0,0],[0,0,0]])
print(v)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [13]:
import numpy as np
v=np.linspace(0,5,10)
print(v)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [29]:
import numpy as np
v=np.eye(5)
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
x3 = np.random.randint(10, size=(3, 4, 5))

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [30]:
m_r = np.random.random((4,4))
print(m_r)

[[0.73130019 0.96990311 0.97251527 0.03598455]
 [0.74352662 0.08476217 0.07105049 0.37109127]
 [0.23213094 0.31076197 0.82328429 0.64932308]
 [0.26712489 0.8508213  0.74466012 0.46755089]]


### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [31]:
import numpy as np
v=np.array([[0,0,0],[0,0,0],[0,0,0]])
print(grip.shape)
#v.shape()

(4, 4)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [24]:
grip=np.arange(1,17).reshape(4,4)
print(grip)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [32]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n.dtype)

int64


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [37]:
n=np.arange(1,101)
l=list()
for i in n:
    if i in n and i%2!=0:
        l.append(i)
print(l)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [39]:
v = np.random.randint(10, 50,size=(1, 6, 6))
print(v)

[[[18 35 40 35 29 21]
  [32 38 43 40 27 13]
  [20 38 48 49 48 29]
  [21 33 17 12 40 18]
  [48 18 45 20 43 45]
  [16 21 30 13 48 13]]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [45]:
b=np.median(v,axis=2)
print(b)

[[32.  35.  43.  19.5 44.  18.5]]


In [46]:
c=np.mean(v,axis=1)
print(c)

[[25.83333333 30.5        37.16666667 28.16666667 39.16666667 23.16666667]]


In [47]:
print(v)

[[[18 35 40 35 29 21]
  [32 38 43 40 27 13]
  [20 38 48 49 48 29]
  [21 33 17 12 40 18]
  [48 18 45 20 43 45]
  [16 21 30 13 48 13]]]


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [50]:
min_v=np.min(v)
#min_v=np.min(v, axis=1)
print(min_v)

12


In [51]:
max_v=np.max(v)
#min_v=np.min(v, axis=1)
print(max_v)

49


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [64]:
n=np.random.randint(20,size=(5,9))
print(n)

[[12  1  1  5 16  0  6  6  9]
 [13 18  6 14  4  7  4 10  5]
 [ 1 10 17 13  2 14 18  0  0]
 [18  0 12 11 11 17 16 12  4]
 [11  4 13 12 19 14 18 13 14]]


In [63]:
mx_n=np.max(n)
print(mx_n)

19


### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [66]:
o=np.random.randint(40,size=(5,5))
c= np.linalg.inv(o)
print(o)
print("=========================================================================")


print(c)

[[38 24 16 31 29]
 [ 9 36 28  8  5]
 [28 11  1 21  1]
 [ 2 17 32 19 18]
 [ 0 14 35  1 19]]
[[-0.00467216 -0.00986586  0.04839003 -0.04429313  0.04914253]
 [ 0.02320143  0.0439228  -0.04531088 -0.00412747 -0.04067633]
 [-0.03497774 -0.0139337   0.05173043  0.0030527   0.05143915]
 [-0.00652848 -0.00889259  0.00733621  0.06135087 -0.04620331]
 [ 0.0476805  -0.00622881 -0.06229205 -0.0058111  -0.00972097]]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [78]:
d=np.dot(o,c)


print(d)

[[ 1.00000000e+00  2.86229374e-17  2.08166817e-17  2.48065457e-16
  -1.73472348e-16]
 [ 7.63278329e-17  1.00000000e+00  7.63278329e-17  3.98986399e-17
   4.85722573e-17]
 [-6.93889390e-18 -5.11743425e-17  1.00000000e+00  2.48065457e-16
   9.02056208e-17]
 [-1.38777878e-17 -1.90819582e-17  9.71445147e-17  1.00000000e+00
   1.52655666e-16]
 [ 9.02056208e-17 -2.86229374e-17  9.02056208e-17  1.73472348e-18
   1.00000000e+00]]


In [81]:
z=np.dot(o*c,3)
print(z)

[[-0.53262569 -0.71034167  2.32272149 -4.11926136  4.27540045]
 [ 0.62643871  4.74366277 -3.80611431 -0.09905933 -0.6101449 ]
 [-2.93813047 -0.45981196  0.1551913   0.19232037  0.15431746]
 [-0.03917091 -0.45352201  0.70427647  3.4969997  -2.49497879]
 [ 0.         -0.26160984 -6.54066538 -0.0174333  -0.55409557]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [82]:
f=np.diag(o)
print(f)

[38 36  1 19 19]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [102]:
p=np.random.randint(10,size=(3,3))
q=np.random.randint(10,size=(3,3))
h=np.dot(p,q)
print(p)
print("=========================================================================")



print(q)
print("=========================================================================")


print(h)

[[1 9 8]
 [6 7 9]
 [1 6 1]]
[[3 0 8]
 [7 7 9]
 [1 8 6]]
[[ 74 127 137]
 [ 76 121 165]
 [ 46  50  68]]


# Exercise 21:

Stack two NumPy arrays vertically.



In [103]:
np.vstack([p,q])

array([[1, 9, 8],
       [6, 7, 9],
       [1, 6, 1],
       [3, 0, 8],
       [7, 7, 9],
       [1, 8, 6]])

# Exercise 20:

Flatten a 2D NumPy array into a 1D array.




In [108]:
k=np.random.randint(10,size=(2,2))
print(k)
print("=========================================================================")


k.flatten()

[[1 0]
 [9 6]]


array([1, 0, 9, 6])

# Exercise 22:

Stack two NumPy arrays horizontally.




In [111]:
l=np.random.randint(10,size=(5,5))
i=np.random.randint(10,size=(5,5))
print(l)
print("=========================================================================")

print(i)
print("=========================================================================")


np.hstack([l,i])

[[0 3 7 5 4]
 [7 2 8 4 6]
 [6 4 5 6 4]
 [7 7 3 1 3]
 [5 2 7 2 3]]
[[1 8 3 1 4]
 [9 3 1 4 4]
 [0 5 1 2 4]
 [9 6 1 0 4]
 [7 2 0 2 1]]


array([[0, 3, 7, 5, 4, 1, 8, 3, 1, 4],
       [7, 2, 8, 4, 6, 9, 3, 1, 4, 4],
       [6, 4, 5, 6, 4, 0, 5, 1, 2, 4],
       [7, 7, 3, 1, 3, 9, 6, 1, 0, 4],
       [5, 2, 7, 2, 3, 7, 2, 0, 2, 1]])

# Exercise 23:

Split a NumPy array into multiple sub-arrays.




In [ ]:
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
x=np.split(n)
print(n)
print(x)

# Exercise 24:

Generate a random NumPy array and round each element to two decimal places.

In [55]:
import numpy as np
k=np.random.random((5,5))
c=np.round(k,2)
print(k)
print("=========================================================================")

print(c)

[[0.92477118 0.28595324 0.11121934 0.75400523 0.42749216]
 [0.56833774 0.02627061 0.28911392 0.89360078 0.85421097]
 [0.79978599 0.42041603 0.06387449 0.04263369 0.45073929]
 [0.754462   0.15926358 0.25932906 0.41748865 0.39003037]
 [0.28511446 0.2840971  0.1175647  0.23338432 0.37948258]]
[[0.92 0.29 0.11 0.75 0.43]
 [0.57 0.03 0.29 0.89 0.85]
 [0.8  0.42 0.06 0.04 0.45]
 [0.75 0.16 0.26 0.42 0.39]
 [0.29 0.28 0.12 0.23 0.38]]


# Exercise 25:

Find the unique elements of a NumPy array.




In [8]:
t=np.random.randint(10,size=(4,4))
d=np.unique(t)
print(t)
print(d)

[[2 7 5 9]
 [5 6 5 9]
 [4 4 7 9]
 [9 2 8 0]]
[0 2 4 5 6 7 8 9]



# Exercise 26:

Replace all elements in a NumPy array that are less than a specific value with that value.




In [13]:
T=np.random.randint(20,size=(4,4))
T[T<10]=2
print('modify matrix: \n',T)

modify matrix: 
 [[12  2  2  2]
 [ 2 14  2  2]
 [ 2 14  2 15]
 [11  2  2  2]]



# Exercise 27:

Find the cumulative sum of the elements in a NumPy array

In [53]:
H=np.random.randint(20,size=(3,3))
H1=np.cumsum(H)
print(H)
print("=========================================================================")

print(H1)

[[ 5 18 12]
 [ 2 10  9]
 [14 18 11]]
[ 5 23 35 37 47 56 70 88 99]



# Exercise 29:

Create a NumPy array of random integers and sort it in ascending order.


In [19]:
H.sort()
print`b(H)

[[ 3  7 18]
 [ 3  8 10]
 [ 2 18 18]]



# Exercise 30:

Find the row-wise and column-wise sum of a 3x3 matrix.


In [54]:
H2=np.random.randint(20,size=(5,5))
H3=np.random.randint(20,size=(5,5))
print(H2)
print("=========================================================================")

print(H3)
print("=========================================================================")
print(H2+H3)

[[ 1 18 14 10  8]
 [ 8  9  7 18 15]
 [ 1  0  9  0  1]
 [ 7  9 17 16  7]
 [ 3 17 12  0 15]]
[[ 4  8  3  8  4]
 [ 9 13 17  1 13]
 [13  3  8 18 12]
 [16  0  8 14 15]
 [16  9  1 10  2]]
[[ 5 26 17 18 12]
 [17 22 24 19 28]
 [14  3 17 18 13]
 [23  9 25 30 22]
 [19 26 13 10 17]]


# exercise31
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [29]:
H2=np.random.random((2,2))
H3=np.linalg.norm(H2,axis=1)
print(H2)
print("=========================================================================")
print(H3)

[[0.51898395 0.04682326]
 [0.66214121 0.07257322]]
[0.52109189 0.66610649]


# Exercise 32:

Create two NumPy arrays and find the dot product.




In [52]:
H4=np.random.randint(5,size=(5,5))
H5=np.random.randint(5,size=(5,5))
H6=np.dot(H4,H5)
print(H4)
print("=========================================================================")

print(H5)
print("=========================================================================")

print(H6)

[[2 1 1 2 1]
 [4 3 4 1 3]
 [1 3 2 0 4]
 [3 3 2 0 4]
 [3 3 3 1 1]]
[[3 4 4 3 1]
 [1 3 0 0 2]
 [0 1 0 3 2]
 [4 1 4 3 0]
 [3 0 4 4 4]]
[[18 14 20 19 10]
 [28 30 32 39 30]
 [18 15 20 25 27]
 [24 23 28 31 29]
 [19 25 20 25 19]]


# Exercise 33:

Find the trace of a square NumPy matrix.



In [33]:
H7=np.trace(H6)
print(H7)

107



# Exercise 34:

Create a 2D array and swap two rows.




In [39]:
H8=np.random.randint(5,size=(2,2))
H9= H8[[1, 0]]
print(H8)
print(H9)

[[4 2]
 [3 3]]
[[3 3]
 [4 2]]


# Exercise 35:

Create a 1D NumPy array and convert it into a column vector.




In [49]:
H8=np.array([1,2,3,4,5,6,7,8,9])
colum=H8[:,np.newaxis]
print(H8)

[1 2 3 4 5 6 7 8 9]


# Exercise 36:

Find the determinant of a 3x3 matrix.




In [51]:
H8=np.random.randint(5,size=(3,3))
det_H8=np.linalg.det(H8)
print(H8)
print("=========================================================================")

print(det_H8)

[[4 4 3]
 [3 2 3]
 [4 4 4]]
-4.0
